### ISSUE TITLE
Setting active skill to TimeSkill too often

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/skill-date-time#13]
Logs should be self explanatory (look at the timestamps):

```
14:51:48.160 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:48.162 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:48.164 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:48.165 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:48.166 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:48.167 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:48.167 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.171 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.173 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.174 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.175 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.176 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.177 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
14:51:53.178 - mycroft.client.enclosure.display_manager:set_active:106 - DEBUG - Setting active skill to TimeSkill
```

**Comment by rigved** [comment]
Facing the same issue. More details from the logs (if that helps):

```
11:40:23.873 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "data": {"session": "xxx", "utterance": "hey mycroft"}, "context": null}
11:40:23.884 - SKILLS - DEBUG - {"type": "Command: mouth.reset", "data": {}, "context": null}
11:40:26.144 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-US", "session": "xxx": ["what time is it"]}, "context": null}
11:40:26.154 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": 1017122086, "utterances": ["what time is it"]}, "context": null}
11:40:26.164 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 1017122086, "result": false}, "context": null}
11:40:26.291 - SKILLS - DEBUG - {"type": "1017122086:SpeakIntent", "data": {"confidence": 1.0, "target": null, "intent_type": "1017122086:SpeakIntent", "TimeKeyword": "time", "__tags__": [{"end_token": 0, "start_
token": 0, "from_context": false, "entities": [{"confidence": 1.0, "data": [["what", "QueryKeyword"]], "key": "what", "match": "what"}], "key": "what", "match": "what"}, {"end_token": 1, "start_token": 1, "from_c
ontext": false, "entities": [{"confidence": 1.0, "data": [["time", "TimeKeyword"]], "key": "time", "match": "time"}], "key": "time", "match": "time"}], "QueryKeyword": "what", "utterance": "what time is it"}, "co
ntext": {"target": null}}
11:40:26.308 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.312 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "TimeSkill.handle_speak_intent"}, "context": null}
11:40:26.330 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": false, "utterance": "It is 17:10"}, "context": null}
11:40:26.333 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.346 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.361 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.372 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.387 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.399 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.409 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.419 - mycroft.client.enclosure.display_manager:set_active:101 - DEBUG - Setting active skill to TimeSkill
11:40:26.434 - mycroft.skills.core:wrapper:371 - ERROR - An error occurred while processing a request in TimeSkill
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.0-py2.7.egg/mycroft/skills/core.py", line 358, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-date-time/__init__.py", line 170, in handle_speak_intent
    self._update_time()
  File "/opt/mycroft/skills/skill-date-time/__init__.py", line 163, in _update_time
    self.timer.start()
  File "/usr/lib/python2.7/threading.py", line 739, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
11:40:26.486 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": false, "utterance": "An error occurred while processing a request in TimeSkill"}, "context": null}
11:40:26.488 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"exception": "threads can only be started once", "handler": "TimeSkill.handle_speak_intent"}, "context": null}
11:40:26.492 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "TimeSkill.handle_speak_intent"}, "context": null}
```

**Comment by penrods** [comment]
This PR #19 should address things.  But be aware that a skill is considered "active" if it is controlling a display, so when Show Time when Idle is checked then this skill will remain on the active list.

**Comment by penrods** [comment]
I think this is dealt with now.
