### ISSUE TITLE
Interesting error after LF refactor

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/skill-date-time#91]
This is probably LF's problem, but I'm not sure where to start, because all of LF's datetime tests are passing. Anything with a relative datetime, such as, "What is tomorrow's date?" gives me this (sorry about the formatting, plucked from tmux via `bat`):

```
2020-10-10 16:07:59.842 | ERROR    | 2049370 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:835 │
  | An error occurred while processing a request in Time Skill                                            │
   Traceback (most recent call last):                                                                     │
     File "/home/chance/development-mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66│
  , in wrapper                                                                                            │
       handler(message)                                                                                   │
     File "/opt/mycroft/skills/mycroft-date-time.mycroftai/__init__.py", line 552, in handle_query_relativ|
	e_date_alt
                                                                                                          │
       self.handle_query_date(message, response_type="relative")                                          │
     File "/opt/mycroft/skills/mycroft-date-time.mycroftai/__init__.py", line 506, in handle_query_date   │
       num_days = (day_date - today_date).days                                                            │
   TypeError: can't subtract offset-naive and offset-aware datetimes
```

I'd love to troubleshoot this, because nobody wants to merge breaking changes, but, yeah, this is what I'm getting at LF's end:

```python3
>>> from lingua_franca import load_language, parse
>>> load_language('en')
>>> parse.extract_datetime("tomorrow")
[datetime.datetime(2020, 10, 11, 0, 0), '']
>>> parse.extract_datetime("tomorrow's date")
[datetime.datetime(2020, 10, 11, 0, 0), 'date']
>>> parse.extract_datetime("what day is tomorrow")
[datetime.datetime(2020, 10, 11, 0, 0), 'what day is']
>>> parse.extract_datetime("what is tomorrow's date")
[datetime.datetime(2020, 10, 11, 0, 0), 'what is date']
```

As of this writing, Mycroft + LF refactor can be tested from [my fork](https://github.com/ChanceNCounter/lingua_franca) branch `lf-refactor`, which is the branch getting this error

**Comment by forslund** [comment]
I think the issue is that you removed the extract_datetime() wrapper from core. It injected an anchordate with the local time including the tz info as configured in Mycroft.

**Comment by ChanceNCounter** [comment]
Well, good catch, but putting the ~~refactor~~ wrapper back got me `I could not find that date for you` on all requests, which is in one sense a step backward cuz it was doing `today` and `the date` just fine.

This is now a thing.

**Comment by forslund** [comment]
This seems to work:

```python
from lingua_franca.parse import extract_datetime as lf_extract_datetime         
                                                                                
def extract_datetime(text, anchorDate=None, lang=None, default_time=None):      
    return lf_extract_datetime(text, anchorDate or now_local(),                 
                               lang=lang or get_default_lang(),                 
                               default_time=default_time)                       
 ```

Not sure of the get_default_lang() can't get it to work without it due to the lang parameter being passed to the english version of the extract_datetime

**Comment by forslund** [comment]
Maybe this is more in line with LF:

```python
from lingua_franca.parse import extract_datetime as lf_extract_datetime       
                                                                                
def extract_datetime(text, anchorDate=None, lang=None, default_time=None):    
      if lang is None:                                                          
          return lf_extract_datetime(text, anchorDate or now_local(),           
                                     default_time=default_time)                 
      else:                                                                     
          return lf_extract_datetime(text, anchorDate or now_local(),           
                                     lang=lang,                                 
                                     default_time=default_time)
```

Only send the lang parameter if it's set.

**Comment by ChanceNCounter** [comment]
You're definitely on the right track, I'll bring that in for the moment.

`lingua_franca.set_default_lang()` is called in `SkillManager.py` (Jarbas' suggestion for an early, sensible place to read user config.) This should enable you to omit the `lang` parameter entirely, and LF will just call whatever the user's expecting.

**Comment by forslund** [comment]
Yeah, omitted works, while lang=None causes an error

**Comment by ChanceNCounter** [comment]
By now, I'd imagine, if this were still happening, several of us would have been murdered by users.
